config/routes.rb
ThatStatBook::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => 'passwords', :registrations => 'registrations' }

  root 'pages#welcome'

  get '/home' => 'users#dashboard', as: :user_dashboard
  get '/summary' => 'users#summary', as: :user_summary
  get '/feedback' => 'users#feedback', as: :feedback
  
  resources :users, only: [:show,:index,:destroy]
  resources :lessons, only: [:show,:index,:update,:destroy,:new,:create] do
    collection { post :sort }
    resources :questions, only: [:new,:create]
    resources :videos, only: [:new,:create]
    resources :learning_modules, only: [:index,:create,:new,:destroy]
  end
  
  resources :learning_modules, only: [:update]
  resources :quizzes, only: [:create,:show]
  resources :questions, only: [:show,:destroy,:update]
  resources :choices, only: [:show,:update]
  resources :answer_submissions, only: [:create]
  resources :video_views, only: [:create]
  
  resources :rosters, only: [:index,:show,:new,:update,:create]
  
  resources :class_requests, only: [:create, :index]
  
  resources :suggestions do
    get :autocomplete_school_school, :on => :collection
  end

  get '/questions/:id/update_learning_module/:learning_module_id' => 'questions#update_learning_module'

  get '/quizzes/:quiz_id/new-question' => 'questions#show_random_question', as: :random_question
  get '/quizzes/:quiz_id/incomplete' => 'quizzes#incomplete'
  get '/quizzes/:quiz_id/certificate' => 'quizzes#certificate', as: :certificate
  get '/quizzes/:id/feedback' => 'quizzes#feedback', as: :quiz_feedback
  
  get 'rearrange' => 'lessons#rearrange'
  
  get 'password-reset' =>'pages#password_reset', as: :password_reset
  
  post '/countdown' => 'quizzes#countdown'
  
  get '/questions/:id/delete_image' => 'questions#delete_image', as: :delete_question_image
  
  patch '/rosters/:id/add_students' => 'rosters#add_students', as: :add_students
  post '/rosters/:id/remove_student/:user_id' => 'rosters#remove_student', as: :remove_student  
  get '/rosters-prof/:prof_id' => 'rosters#get_rosters_by_prof' 
  
  get '/rosters/:roster_id/students/:student_id' => 'rosters#show_roster_student', as: :student_roster

  get '/class_requests/:id/accept' => 'class_requests#accept', as: :accept_class_request
  get '/class_requests/:id/reject' => 'class_requests#reject', as: :reject_class_request
  
  get '/professors' => 'users#professors_index', as: :professors

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :lesson
  has_many :choices, :dependent => :destroy, inverse_of: :question
  has_many :answer_submissions, through: :choices
  belongs_to :learning_module
  validates_presence_of :question
  validates_presence_of :lesson_id
  accepts_nested_attributes_for :choices
  has_attached_file :image,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def answer
    self.choices.where(is_correct: true).first
  end
  
  def total_attempts
    self.answer_submissions.size
  end
  
  def correct_attempts
    self.answer_submissions.select{ |ans| ans.choice.is_correct }.size
  end
  
  def percent_correct
    attempts = self.total_attempts
    attempts == 0 ? nil : self.correct_attempts / self.total_attempts
  end
  
  def random_wrong_choice
    self.choices.where(is_correct: false).first
  end
  
  def s3_credentials
    {:bucket => ENV['BUCKET'], :access_key_id => ENV['ACCESS_KEY_ID'], :secret_access_key => ENV['SECRET_ACCESS_KEY']}
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
    @total_questions = ENV['QUIZ_QUESTIONS']
    unless current_user.student?
      @user = current_user
      respond_to do |format|
        format.html {render :show_admin}
        format.json {render :json => @question}
      end
    else
      @choices = @question.choices.shuffle
      @ids = %w[A B C D]
      @quiz = Quiz.find(params[:quiz_id])
      @answer_submission = AnswerSubmission.new
    end
  end
  def show_random_question
    @quiz = Quiz.find(params[:quiz_id])
    @question = @quiz.new_random_question
    redirect_to question_path(id: @question.id, quiz_id: @quiz.id)
  end
  
  def new
    if current_user.admin?
      @lesson = Lesson.find(params[:lesson_id])
      @question = @lesson.questions.new
      4.times { @question.choices.build }
    end
  end
  
  def create
    if current_user.admin?
      @question = Question.new(question_params)
      @question.choices.first.is_correct = true    
      if @question.save
        redirect_to question_path(@question)
      else
        render text: 'ERROR'
      end
    end
  end
  
  def destroy
    if current_user.admin?
      @question = Question.find(params[:id])
      @lesson = @question.lesson
      @question.active = false
      @question.save
      redirect_to lesson_path(@lesson)
    end
  end
  
  def update
    if current_user.admin?
      @question = Question.find(params[:id])
      if @question.update_attributes!(update_question_params)
        respond_to do |format|
          format.html { redirect_to( @question )}
          format.json { render :json => @question }
        end
      end
    end
  end
  
  def update_learning_module
    if current_user.admin?
      @question = Question.find(params[:id])
      @learning_module = LearningModule.find(params[:learning_module_id])
      @question.update!(learning_module: @learning_module)
      redirect_to lesson_path(@question.lesson)
    end
  end
  
  def delete_image
    @question = Question.find(params[:id])
    @question.image = nil
    @question.save
    redirect_to question_path(@question)
  end
  
  private
  def question_params
    params.require(:question).permit(:question,:image,:lesson_id,choices_attributes:[:choice])
  end
  def update_question_params
    params.require(:question).permit(:question,:image)
  end
end

app/views/questions/new.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>


  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> New Question </h2>
      <%= bootstrap_form_for @question, url: lesson_questions_path do |f| %>
      <%= f.text_area :question, required: true %>
      <%= f.file_field :image %>
      <%= f.hidden_field :lesson_id, value: @question.lesson.id.to_s %>
      <%= f.fields_for :choices do |c| %>
        <%= c.text_field :choice, required: true %>
      <% end %>
      <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>       
    </div>
  </div>
  
</div>


<script>
$(function() {
  $($('#new_question > .form-group > label')[1]).html('Image - Optional');
  $($('#new_question > .form-group > label')[2]).html('Choice - CORRECT');
});
</script>

app/views/questions/show.html.erb
<div class='row question-nav'>
 <%= render 'users/user_nav' %>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-1 logo hidden-xs'>
      <%= image_tag('logo.png') %>
    </div>
    <div class='col-sm-10'>
    <div class='question-answer'>
      <div class='header'>
        <h3 class='col-xs-8'><strong>Quiz Topic:</strong> <%=@question.lesson.title%></h3>
        <div class='clock'>
          <%= image_tag('clock.png') %>
        </div>
      </div>
      <div class='time'>
        <span class='timer'><%= time(@quiz.time) %></span> mins left
      </div>
      <div class='question-count'>
        <h4>Question <%= @quiz.answer_submissions.size + 1 %> out of <%=@total_questions%>.</h4>
      </div>
      <div class='question'>
        <%=@question.question%><br>
        <% if @question.image.present? %>
          <%= image_tag @question.image.url, class: 'img-responsive' %>
        <% end %>
      </div>
      <div class='answers'>
        <%= form_for @answer_submission, html: {class: 'nifty_form'} do%>
          <% @choices.each_with_index do |choice,index| %>
            <%= radio_button_tag(:choice_id, choice.id)%>
            <%= label_tag('choice_id_'+choice.id.to_s, @ids[index] + '. ' + choice.choice)%><br/>
          <% end %>
          <%= hidden_field_tag :quiz_id, @quiz.id %>
          <div class='submit'>
            <%= submit_tag 'Answer', class: 'btn btn-primary btn-lg' %>
          </div>
        <% end %>
      </div>
      

      
    </div>
    </div>
  </div>
</div>

<script>
var timerFunc = setInterval(function() {
      TimerModel.quizCountDown();
    }, 1000)

</script>

app/views/questions/show_admin.html.erb
<div class='row'>
  <% if @user.admin? %>
    <%= render 'users/admin_nav' %>
  <% else %>
    <%= render 'users/prof_nav' %>
  <% end %>


  <div class='col-sm-9'>
    <div class='dashboard'>
      <%= link_to '< Lesson', lesson_path(@question.lesson) %><br/>
      <div class='question-form'>
      <h2> Question: 
        <span class="rest-in-place" data-url="/questions/<%=@question.id%>" data-object="question" data-attribute="question" data-placeholder="question">
          <%=@question.question%>
        </span>
      </h2>
      <% if @user.admin? %>
      <div class='delete-question'>
        <%= link_to 'Delete Question', question_path(@question), method: :delete, data: { confirm: 'You are about to delete a question. This is irreversible. Are you sure?' }, class: 'btn btn-primary' %>
      </div>
      <% end %>
      
      <div class='question-image'>
        <% if @question.image.present? %>
        <div class='col-sm-10'>
          <div class='question-answer'>
            <div class='question'>
              <%= image_tag @question.image.url, class: 'img-responsive' %>
            </div>
          </div>
        </div>
        <% else %>
          No Image
        <% end %>
      </div>
      
      <% if @user.admin? %>
      <div class='upload-new-image'>
        <%= form_for @question, :url => question_path, :html => { :multipart => true } do |form| %>
          <%= form.file_field :image %>
          <div class='btn-group'>
            <%= form.submit 'Add/Change Image', class: 'btn btn-primary' %>
            <%= link_to 'Delete Image', delete_question_image_path(@question), class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
      <% end %>
    
    
    </div>
      

       
    <div class='question-answer'>
      <table class='table'>
        <thead>
          <tr>
            <th> Answers </th>
          </tr>
        <thead>
        <tbody>
          <% @question.choices.each_with_index do |choice,index| %>
          <tr <% if choice.is_correct %> class='success' <% end %> >
              <td>
                <span class="rest-in-place" data-url="/choices/<%=choice.id%>" data-object="choice" data-attribute="choice" data-placeholder="choice">
                  <%= choice.choice %>
                </span>
              </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  
  </div>
</div>