config/routes.rb
ThatStatBook::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => 'passwords', :registrations => 'registrations' }

  root 'pages#welcome'

  get '/home' => 'users#dashboard', as: :user_dashboard
  get '/summary' => 'users#summary', as: :user_summary
  get '/feedback' => 'users#feedback', as: :feedback
  
  resources :users, only: [:show,:index,:destroy]
  resources :lessons, only: [:show,:index,:update,:destroy,:new,:create] do
    collection { post :sort }
    resources :questions, only: [:new,:create]
    resources :videos, only: [:new,:create]
    resources :learning_modules, only: [:index,:create,:new,:destroy]
  end
  
  resources :learning_modules, only: [:update]
  resources :quizzes, only: [:create,:show]
  resources :questions, only: [:show,:destroy,:update]
  resources :choices, only: [:show,:update]
  resources :answer_submissions, only: [:create]
  resources :video_views, only: [:create]
  
  resources :rosters, only: [:index,:show,:new,:update,:create]
  
  resources :class_requests, only: [:create, :index]
  
  resources :suggestions do
    get :autocomplete_school_school, :on => :collection
  end

  get '/questions/:id/update_learning_module/:learning_module_id' => 'questions#update_learning_module'

  get '/quizzes/:quiz_id/new-question' => 'questions#show_random_question', as: :random_question
  get '/quizzes/:quiz_id/incomplete' => 'quizzes#incomplete'
  get '/quizzes/:quiz_id/certificate' => 'quizzes#certificate', as: :certificate
  get '/quizzes/:id/feedback' => 'quizzes#feedback', as: :quiz_feedback
  
  get 'rearrange' => 'lessons#rearrange'
  
  get 'password-reset' =>'pages#password_reset', as: :password_reset
  
  post '/countdown' => 'quizzes#countdown'
  
  get '/questions/:id/delete_image' => 'questions#delete_image', as: :delete_question_image
  
  patch '/rosters/:id/add_students' => 'rosters#add_students', as: :add_students
  post '/rosters/:id/remove_student/:user_id' => 'rosters#remove_student', as: :remove_student  
  get '/rosters-prof/:prof_id' => 'rosters#get_rosters_by_prof' 
  
  get '/rosters/:roster_id/students/:student_id' => 'rosters#show_roster_student', as: :student_roster

  get '/class_requests/:id/accept' => 'class_requests#accept', as: :accept_class_request
  get '/class_requests/:id/reject' => 'class_requests#reject', as: :reject_class_request
  
  get '/professors' => 'users#professors_index', as: :professors

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :professor
  has_and_belongs_to_many :users
  has_and_belongs_to_many :lessons
  has_many :quizzes, through: :users
  has_many :video_views, through: :users
  has_many :class_requests
  
  def quiz_attempts
    # total_quiz_attempts = []
    # self.lessons.each do |lesson|
    #   self.users.each do |user|
    #     total_quiz_attempts << user.quiz_attempts(lesson.id)
    #   end
    # end
    # total_quiz_attempts.flatten
    
    # Pulls completed quizzes on all users associated with current roster INCL lessons no longer in the roster
    
    self.quizzes.select("quizzes.*").joins(:answer_submissions).group("quizzes.id").having("count(answer_submissions.id) >= ?", 20).to_a
  end
  
  def avg_score
    q_attempts = self.quiz_attempts.clone
    if q_attempts.empty?
      0
    else
      q_attempts.map{|quiz| quiz.score}.sum / q_attempts.size
    end
  end
  
  def view_count
    users = self.users
    users.map { |user| user.roster_view_count(self)}.sum
  end
  
  def stats
    attempts = self.quiz_attempts
    {
      quiz_attempts: attempts.size,
      avg_score: attempts.empty? ? 0 : attempts.map{|quiz| quiz.score}.sum / attempts.size,
      view_count: self.video_views.size
    }
  end
  
  def stats_detailed
    
    
  end
  
  
  
  
  
  
  
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  def index
    if current_user.class == Professor
      @rosters = current_user.rosters.sort!
      @roster_stats = @rosters.map{|roster| [roster,roster.stats] }
      render :index_professor
    elsif current_user.student?
      @class_request = ClassRequest.new
      @user = current_user
      @rosters = current_user.rosters
      @professors = Professor.all.select{ |prof| prof.school == @user.school }
      render :index_student
    elsif current_user.admin?
      @rosters = Roster.all.sort_by{ |roster| roster.professor.list_name }
      render :index_admin
    end
  end
  
  def show
    @roster = Roster.find(params[:id])
    if current_user.class == Professor
      @roster_stats = @roster.stats
      @new_student = User.new
      @all_lessons = Lesson.all.sort_by { |lesson| lesson.level }
      @students = @roster.users.sort_by {|student| student.last_name }
      @student_stats = @students.map{|student| [student,student.stats(@roster)]}
      @all_students = User.all.select{ |user| user.student? }.sort_by{ |student| student.last_name } - @students
      render :show_professor
    elsif current_user.student?
      @accessible_lessons = current_user.accessible_roster_lessons(@roster.id)
      @user = current_user
      @lessons = @roster.lessons.sort_by { |lesson| lesson.level }
      render :show_student
    elsif current_user.admin?
      @roster_stats = @roster.stats
      @students = @roster.users.sort_by {|student| student.last_name }
      @student_stats = @students.map{|student| [student,student.stats(@roster)]}
      render :show_admin
    end
  end
  
  def show_roster_student
    if current_user.class == Professor
      @roster = Roster.find(params[:roster_id])
      @student = User.find(params[:student_id])
      @lessons = @roster.lessons.sort_by { |lesson| lesson.level }
      render :show_roster_student
    end
  end
  
  def new
    if current_user.class == Professor
      @roster = Roster.new
      @all_students = User.all.select{ |user| user.student? }.sort_by{ |student| student.last_name }
    end
  end
  
  def create
    if current_user.class == Professor
      @roster = Roster.new(roster_params)
      @roster.professor = current_user
      if @roster.save
        redirect_to roster_path(@roster)
      else
        render text: 'ERROR'
      end
    end
  end
  
  def update
    if current_user.class == Professor
      @roster = Roster.find(params[:id])
      if @roster.update_attributes!(update_roster_params)
        respond_to do |format|
          format.html {redirect_to roster_path(@roster)}
          format.json {render :json => @roster}
        end
      else
        format.json { render :nothing =>  true }
      end
    end
  end
  
  def add_students
    @roster = Roster.find(params[:id])
    @student_ids = @roster.user_ids
    @student_ids << update_roster_params[:user_ids]
    @student_ids.flatten!
    @roster.update_attributes!({user_ids: @student_ids})
    redirect_to roster_path(@roster)
  end
  
  def remove_student
    @roster = Roster.find(params[:id])
    @student_pending_removal = User.find(params[:user_id])
    @roster.users.delete(@student_pending_removal)
    redirect_to roster_path(@roster)
  end
  
  def get_rosters_by_prof
    @rosters = Professor.find(params[:prof_id]).rosters
    render json: @rosters
  end
  
  private
  
  def roster_params
    params.require(:roster).permit(:title,user_ids: [])
  end
  
  def update_roster_params
    params.require(:roster).permit(:title,user_ids: [],lesson_ids: [])
  end
  
end

app/views/rosters/_edit_lessons.html.erb
 <table id='lessons' class='table table-striped'>
  <%= form_for @roster, url: roster_path(@roster), method: :patch do |f| %>
  <tbody data-update-url="<%= sort_lessons_path %>">
    <% @all_lessons.each do |lesson| %>
    <tr id="lesson_<%= lesson.id %>">
      <td><%= f.check_box("lesson_ids", {multiple: true, checked: @roster.lessons.pluck(:id).include?(lesson.id)}, lesson.id, nil) %></td>
      <td><%= link_to lesson.title, lesson_path(lesson) %></td>
    <% end %>
  </tbody><br/>
  <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</table>

app/views/rosters/_new_class_request.html.erb
<div class='professor-select'>
  <div class='select-wrapper'>
  <%= form_for @class_request do %>
    <h5> Select Professor </h5>
    <%= select_tag 'professor', options_for_select(@professors.map{ |prof| [prof.list_name,prof.id] }),id: 'professor-list', :size => 5 %>
    <h5> Select Class </h5>
    <div id='class-select'>
      <select id='roster-list' name='roster' size='5'></select>
    </div>
    <%= submit_tag 'Send Request', class: 'btn btn-primary btn-md' %>
  <% end %>
  </div>
</div>

app/views/rosters/_student_select.html.erb
<%= label_tag 'Add Students' %>
<div class='student-search'>
  <input class='form-control' placeholder='Search Students...' id='student-search'>
</div>
<div class='student-select'>
  <div class='select-wrapper'>
    <%= select_tag 'users[]', options_for_select(@all_students.map{ |student| [student.list_name,student.id] }),id: 'student-list', class: 'existing-students', :multiple => true, :size => 10 %>
    <%= select_tag 'roster[user_ids]', options_for_select([]), class: 'confirmed-students', :multiple => true, :size => 10 %>
    <a href='#' id='move-student'>
      <i class="fa fa-caret-right"></i>
    </a>
  </div>
</div>

app/views/rosters/index_admin.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>
 
 
  <div class='lessons col-sm-9'>
    <div class='dashboard'>
      <h2> Classes </h2>
  
  <table class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>Class</th>
          <th>Professor</th>
          <th>Number of Students</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @rosters.each do |roster| %>
          <tr>
            <td><%= roster.title %></td>
            <td><%= roster.professor.list_name %></td>
            <td><%= roster.users.size %></td>
            <td><%= link_to 'More Details', roster_path(roster) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rosters/index_professor.html.erb
<div class='row'>
 <%= render 'users/prof_nav' %>
 
 <div class='col-sm-9'>
  <div class='lessons dashboard'>
    <h2> My Classes </h2>        
    <%= link_to 'New Class', new_roster_path, class: 'btn btn-primary' %> 
    <table id='lessons' class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>CLASS</th>
          <th>VIDEO VIEWS</th>
          <th>QUIZ ATTEMPTS</th>
          <th>QUESTIONS</th>
          <th>STUDENTS</th>
        </tr>
      </thead>
      <tbody data-update-url="<%= sort_lessons_path %>">
        <% @roster_stats.each do |roster| %>
        <tr id="roster_<%= roster[0].id %>">
          <td><%= link_to roster[0].title, roster_path(roster[0]) %></td>
          <td><%= roster[1][:view_count] %></td>
          <td><%= roster[1][:quiz_attempts] %></td>
          <td><%= percent(roster[1][:avg_score]) %></td>
          <td><%= roster[0].users.size %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rosters/index_student.html.erb
<div class='row'>
  <%= render 'users/user_nav' %>
  <div class='col-sm-9'>
    <div class='rosters-index lessons dashboard'>
      <h2 class='heading'> My Classes </h2>        
      <button class='btn btn-primary btn-md' data-toggle='modal' data-target='#newClassRequest'>Request to be Added to a Class</button>
      <table id='lessons' class='table table-striped'>
        <thead>
          <tr>
            <th class ='left'>CLASS</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>QUESTIONS</th>
            <th>STUDENTS</th>
          </tr>
        </thead>
        <tbody data-update-url="<%= sort_lessons_path %>">
          <% @rosters.each do |roster| %>
          <tr id="roster_<%= roster.id %>">
            <td><%= link_to roster.title, roster_path(roster) %></td>
            <td><%= @user.roster_view_count(roster) %></td>
            <td><%= @user.roster_quiz_attempts(roster).size %></td>
            <td><%= percent(@user.roster_avg_score(roster))%></td>
            <td><%= roster.users.size%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal fade" id="newClassRequest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Class Request</h4>
      </div>
      <div class="modal-body">
        <%= render 'new_class_request' %>
      </div>
    </div>
  </div>
</div>
  

app/views/rosters/new.html.erb
<div class='row'>
  <%= render 'users/prof_nav' %>
  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> New Class </h2>
      <%= bootstrap_form_for @roster, url: rosters_path do |f| %>
      <%= f.text_field :title, required: true %>
      <%= render 'student_select'%>
      <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/rosters/show_admin.html.erb
<div class='row'>
  <%= render 'users/admin_nav' %>
  
  <div class='rosters col-sm-9'>
    <div class='lessons dashboard'>
      <h2><%= @roster.title %></h2>
      <div class='roster-stats lesson-stats'>
        <ul>
          <li>
            <div class='header'>Views</div>
            <div class='stat'><%= @roster_stats[:view_count] %></div>
          </li>
          <li>
            <div class='header'>Quiz Attempts</div>
            <div class='stat'><%= @roster_stats[:quiz_attempts] %></div>
          </li>
          <li>
            <div class='header'>Average Score</div>
            <div class='stat'><%= percent(@roster_stats[:avg_score]) %></div>
          </li>
        </ul>
      </div>
      <br/>
      <table id='students' class='table table-striped'>
        <thead>
          <tr>
            <th class ='left'>STUDENT</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>QUESTIONS</th>
          </tr>
        </thead>
        <tbody data-update-url="<%= sort_lessons_path %>">
          <% @student_stats.each do |student| %>
          <tr id="student_<%= student.id %>">
            <td><%= student[0].name %></td>
            <td><%= student[1][:view_count] %></td>
            <td><%= student[1][:quiz_attempts] %></td>
            <td><%= percent(student[1][:avg_score]) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/rosters/show_professor.html.erb
<div class='row'>
  <%= render 'users/prof_nav' %>
  
  <div class='rosters col-sm-9'>
    <div class='lessons dashboard'>
      <h2>
        <span class="rest-in-place" data-url="/rosters/<%=@roster.id%>" data-object="roster" data-attribute="title" data-placeholder="roster">
          <%= @roster.title %> 
        </span>
      </h2>
      <div id='accordion'>
        <div class='roster-controls'>
          <%= link_to 'Add Students','',  data: {toggle: 'modal', target: '#myModal'}, class: 'btn btn-primary' %>
          <%= link_to 'Edit Lessons','#editLessons',  data: {toggle: 'collapse', parent: '#accordion'}, class: 'btn btn-primary' %>
        </div>
        
        <div id='editLessons' class='panel-collapse collapse'>
          <div class='panel-body'>
            <%= render 'edit_lessons' %>
          </div>
        </div>
      </div>
      
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
          <%= form_for @roster, url: add_students_path(@roster), method: :patch do |f| %>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title" id="myModalLabel">Add Students</h4>
            </div>
            <div class="modal-body">
              <%= render 'student_select'%>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit 'Update', class: 'update-students-btn btn btn-primary' %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class='roster-stats lesson-stats'>
        <ul>
          <li>
            <div class='header'>Views</div>
            <div class='stat'><%= @roster_stats[:view_count] %></div>
          </li>
          <li>
            <div class='header'>Quiz Attempts</div>
            <div class='stat'><%= @roster_stats[:quiz_attempts] %></div>
          </li>
          <li>
            <div class='header'>Average Score</div>
            <div class='stat'><%= percent(@roster_stats[:avg_score]) %></div>
          </li>
        </ul>
      </div>
      <br/>
      <table id='students' class='table table-striped'>
        <thead>
          <tr>
            <th class ='left'>STUDENT</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>QUESTIONS</th>
            <th></th>
          </tr>
        </thead>
        <tbody data-update-url="<%= sort_lessons_path %>">
          <% @student_stats.each do |student| %>
          <tr id="student_<%= student[0].id %>">
            <td><%= link_to student[0].name, student_roster_path(@roster.id,student[0].id) %></td>
            <td><%= student[1][:view_count] %></td>
            <td><%= student[1][:quiz_attempts] %></td>
            <td><%= percent(student[1][:avg_score]) %></td>
            <td><%= link_to "<i class='fa fa-trash-o'></i>".html_safe, remove_student_path(@roster.id,student[0].id), method: :post,data: { confirm: 'You are about to remove this student from your roster. Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/rosters/show_roster_student.erb
<div class='row'>
  <%= render 'users/prof_nav' %>
  <div class='col-sm-9'>
    <div class='roster lessons dashboard'>
      <h2> <%= @roster.title %> - <%= @student.name %> </h2>        
      <table id='lessons' class='table table-striped'>
        <thead>
          <tr>
            <th width='70%' class ='left'>LESSON</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>AVG SCORE</th>
            <th>LATEST FEEDBACK</th>
          </tr>
        </thead>
        <tbody id='accordion' data-update-url="<%= sort_lessons_path %>">
          <% @lessons.each do |lesson| %>
          <tr id="lesson_<%= lesson.id %>">
            <td><%= lesson.title %></td>
            <td><%= @student.view_count(lesson.id) %></td>
            <td><%= @student.quiz_attempts(lesson.id).size %></td>
            <td><%= percent(@student.avg_score(lesson.id))%></td>
            <% quiz = @student.last_completed_quiz(lesson.id) %>
            <td><%= link_to 'LATEST FEEDBACK', quiz_path(quiz), class: 'btn btn-primary' unless quiz.nil? %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

app/views/rosters/show_student.html.erb
<div class='row'>
  <%= render 'users/user_nav' %>
  <div class='col-sm-9'>
    <div class='roster lessons dashboard'>
      <h2> <%= @roster.title %> </h2>
      <table id='lessons' class='table table-striped'>
        <thead>
          <tr>
            <th width='70%' class ='left'>LESSON</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>AVG SCORE</th>
          </tr>
        </thead>
        <tbody id='accordion' data-update-url="<%= sort_lessons_path %>">
          <% @lessons.each do |lesson| %>
          <tr id="lesson_<%= lesson.id %>">
            <td>
              <% if @accessible_lessons.include?(lesson.id)%>
              <a href='#openLesson<%=lesson.id%>' data-toggle='collapse' data-parent='#accordion'>
                <%= lesson.title %>
              </a>
              <% else %>
                <%= lesson.title %>
              <% end %>
            </td>
            <td><%= @user.view_count(lesson.id) %></td>
            <td><%= @user.quiz_attempts(lesson.id).size %></td>
            <td><%= percent(@user.avg_score(lesson.id))%></td>
            </tr>
            <tr id='openLesson<%=lesson.id%>' class='panel-collapse collapse'>
              <td colspan="4">
                <div class='current-lesson'>
                  <div class='header'>
                    Topic: <strong><%= lesson.title %></strong>
                  </div>
                  <div class='video-preview'>
                    <% lesson.videos.each do |video| %>
                    <video controls="controls" data-user-id=<%=@user.id%> data-video-id=<%=video.id%>>
                      <source src=<%=video.video%> type=<%=video.video_content_type%>>
                      <source src=<%=video.ogv_video%> type=<%=video.ogv_video_content_type%>>
                    </video>
                    <% end %>
                  </div>
                  <div class='take-assessment'>
                    <%= form_for Quiz.new, url: quizzes_path, html:{class: 'nifty_form'} do %>
                      <%= hidden_field_tag :lesson_id, lesson.id %>
                      <%= hidden_field_tag :roster_id, @roster.id %>
                      <%= submit_tag 'TAKE THE QUIZ', class: 'btn btn-primary btn-lg' %>
                    <%end%>
                  </div>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
        
<script>
  $(function() {
    videoView();
  })
</script>