config/routes.rb
ThatStatBook::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => 'passwords', :registrations => 'registrations' }

  root 'pages#welcome'

  get '/home' => 'users#dashboard', as: :user_dashboard
  get '/summary' => 'users#summary', as: :user_summary
  get '/feedback' => 'users#feedback', as: :feedback
  
  resources :users, only: [:show,:index,:destroy]
  resources :lessons, only: [:show,:index,:update,:destroy,:new,:create] do
    collection { post :sort }
    resources :questions, only: [:new,:create]
    resources :videos, only: [:new,:create]
    resources :learning_modules, only: [:index,:create,:new,:destroy]
  end
  
  resources :learning_modules, only: [:update]
  resources :quizzes, only: [:create,:show]
  resources :questions, only: [:show,:destroy,:update]
  resources :choices, only: [:show,:update]
  resources :answer_submissions, only: [:create]
  resources :video_views, only: [:create]
  
  resources :rosters, only: [:index,:show,:new,:update,:create]
  
  resources :class_requests, only: [:create, :index]
  
  resources :suggestions do
    get :autocomplete_school_school, :on => :collection
  end

  get '/questions/:id/update_learning_module/:learning_module_id' => 'questions#update_learning_module'

  get '/quizzes/:quiz_id/new-question' => 'questions#show_random_question', as: :random_question
  get '/quizzes/:quiz_id/incomplete' => 'quizzes#incomplete'
  get '/quizzes/:quiz_id/certificate' => 'quizzes#certificate', as: :certificate
  get '/quizzes/:id/feedback' => 'quizzes#feedback', as: :quiz_feedback
  
  get 'rearrange' => 'lessons#rearrange'
  
  get 'password-reset' =>'pages#password_reset', as: :password_reset
  
  post '/countdown' => 'quizzes#countdown'
  
  get '/questions/:id/delete_image' => 'questions#delete_image', as: :delete_question_image
  
  patch '/rosters/:id/add_students' => 'rosters#add_students', as: :add_students
  post '/rosters/:id/remove_student/:user_id' => 'rosters#remove_student', as: :remove_student  
  get '/rosters-prof/:prof_id' => 'rosters#get_rosters_by_prof' 
  
  get '/rosters/:roster_id/students/:student_id' => 'rosters#show_roster_student', as: :student_roster

  get '/class_requests/:id/accept' => 'class_requests#accept', as: :accept_class_request
  get '/class_requests/:id/reject' => 'class_requests#reject', as: :reject_class_request
  
  get '/professors' => 'users#professors_index', as: :professors

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :belts, uniq: true
  belongs_to :school
  has_and_belongs_to_many :rosters
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :quizzes, :dependent => :destroy
  has_many :video_views, :dependent => :destroy
  validates_presence_of :email
  validates_uniqueness_of :email, :case_sensitive => false
  self.inheritance_column = :type
  has_many :class_requests

  def name
    self.first_name.capitalize + ' ' + self.last_name.capitalize
  end
  
  def list_name
    self.last_name.capitalize + ', ' + self.first_name.capitalize
  end
  
  def student?
    !self.admin? && self.type.nil?
  end
  
  def member_type
    if self.student?
      'Student'
    elsif self.admin?
      'Admin'
    else
      self.type
    end
  end

  def completed_quizzes
    self.quizzes.select {|quiz| quiz.complete? && quiz.belt?}
  end
  
  def completed_roster_quizzes(roster_id)
    self.quizzes.select {|quiz| quiz.complete? && quiz.roster_id == roster_id}
  end
  
  def last_completed_quiz(lesson_id)
    self.completed_quizzes.select{ |quiz| quiz.lesson.id == lesson_id }.sort_by{ |quiz| quiz.created_at }.last
  end

  def passed_quizzes
    self.completed_quizzes.select {|quiz| quiz.pass?}
  end
  
  def passed_roster_quizzes(roster_id)
    self.completed_roster_quizzes(roster_id).select {|quiz| quiz.pass?}
  end

  def completed_levels
    completed_levels = []
    self.passed_quizzes.each {|quiz| completed_levels |= [quiz.lesson.level]}
    completed_levels
  end

  def completed_lessons
    completed_lessons = []
    self.passed_quizzes.each {|quiz| completed_lessons |= [quiz.lesson]}
    completed_lessons
  end
  
  def attempted_lessons
    self.completed_quizzes.map { |quiz| quiz.lesson }.uniq
  end
  
  def completed_roster_lessons(roster_id)
    completed_lessons = []
    self.passed_roster_quizzes(roster_id).each {|quiz| completed_lessons |= [quiz.lesson]}
    completed_lessons
  end

  def level
    self.completed_levels.max.to_i + 1
  end

  def update_belts
    unless self.completed_lessons.empty?
      belt = self.completed_lessons.last.belt
      lessons = belt.lessons
      passes = lessons.map { |lesson| self.completed_lessons.include?(lesson) }
      self.belts << belt unless passes.include?(false)
      self.belts.uniq!
      self.save
    end
  end
  
  def access?(level)
    accessible = self.completed_levels
    accessible << self.level
    accessible.include?(level)
  end

  def assigned_lesson
    Lesson.find_by(level: self.level).nil? ? Lesson.all.sort_by{ |lesson| lesson.level}.last : Lesson.find_by(level: self.level)
  end
  
  def assigned_roster_lesson(roster_id)
    lessons = Roster.find(roster_id).lessons.all.sort_by { |lesson| lesson.level }
    remaining_lessons = lessons - self.completed_roster_lessons(roster_id)
    remaining_lessons.first
  end
  
  def accessible_roster_lessons(roster_id)
    accessible = self.completed_roster_lessons(roster_id)
    accessible << self.assigned_roster_lesson(roster_id) unless self.assigned_roster_lesson(roster_id).nil?
    accessible.map{ |lesson| lesson.id }
  end
  
  def last_incomplete_quiz(lesson_id)
    quizzes_for_lesson = self.quizzes.select { |quiz| quiz.lesson_id == lesson_id && quiz.belt?}
    incomplete_quizzes = quizzes_for_lesson.select {|quiz| !quiz.complete?}
    incomplete_quizzes.last
  end
  
  def last_incomplete_roster_quiz(lesson_id,roster_id)
    quizzes_for_lesson = self.quizzes.select { |quiz| quiz.lesson_id == lesson_id && quiz.roster_id == roster_id}
    incomplete_quizzes = quizzes_for_lesson.select {|quiz| !quiz.complete?}
    incomplete_quizzes.last
  end

  def ninja_status
    self.completed_lessons.size.to_f / Lesson.all.size
  end
  
  
  #Lesson Level Stats
  
  def quiz_attempts(lesson_id)
    self.quizzes.select {|quiz| quiz.complete? }.select { |quiz| quiz.lesson_id == lesson_id }
  end
  
  def avg_score(lesson_id)
    lesson_quizzes = self.quiz_attempts(lesson_id)
    if lesson_quizzes.empty?
      0
    else
      sum = lesson_quizzes.map { |quiz| quiz.score }.sum
      sum / lesson_quizzes.size
    end
  end
    
  def view_count(lesson_id)
    lesson = Lesson.find(lesson_id)
    if lesson.videos.empty?
      0
    else
      video_id = lesson.videos.first.id
      self.video_views.where(video_id: video_id).size
    end
  end
  
  #Roster-Level Stats
  
  def roster_quiz_attempts(roster)
    # lessons = roster.lessons
    # lessons.map{ |lesson| self.quiz_attempts(lesson.id)}.flatten
    self.quizzes.select("quizzes.*").joins(:answer_submissions).group("quizzes.id").having("count(answer_submissions.id) >= ?", 20).to_a
  end
  
  def roster_avg_score(roster)
    if self.roster_quiz_attempts(roster).empty?
      0
    else
      self.roster_quiz_attempts(roster).map{|quiz| quiz.score}.sum / self.roster_quiz_attempts(roster).size
    end
  end
  
  def roster_view_count(roster)
    lessons = roster.lessons
    lessons.map{ |lesson| self.view_count(lesson)}.sum
  end
  
  def stats(roster)
    attempts = self.roster_quiz_attempts(roster)
    {
      quiz_attempts: attempts.size,
      avg_score: attempts.empty? ? 0 : attempts.map{|quiz| quiz.score}.sum / attempts.size,
      view_count: self.video_views.size
    }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    @quiz = Quiz.new
    @lesson = @user.assigned_lesson
    if current_user.admin?
      redirect_to lessons_path
    elsif current_user.student?
      render :user_dashboard
    elsif current_user.class == Professor
      redirect_to rosters_path 
    end
  end
  def summary
    @user = current_user
    if @user.student?
      # @lessons = @user.completed_lessons
      # @lessons << @user.assigned_lesson
      @lessons = Lesson.all.sort_by { |l| l.level }
      @quiz = Quiz.new
      render :summary
    end
  end
  def index
    if current_user.admin?
      @users = User.all.select{|user| user.student?}.sort_by{ |user| user.list_name}
    end
  end
  def professors_index
    if current_user.admin?
      @professors = User.all.select{|user| user.type == 'Professor' }.sort_by{ |user| user.list_name}
    end
  end
  def show
    if current_user.admin?
      @user = User.find(params[:id])
      unless @user.student?
        @rosters = @user.rosters
        render :show_professor
      end
    end
  end
  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    end
  end
  def feedback
    @user = current_user
    if @user.student?
      @lessons = @user.completed_lessons
      @lessons << @user.assigned_lesson
    end
  end
end

app/views/users/_admin_nav.html.erb
  <div class='side-nav'>
    <a href='/'><%= image_tag('dashboard_logo.png') %></a>
    <ul>
      <li <%='class=selected' if current_page?(lessons_path)%>>
        <%= link_to 'Lessons', lessons_path %>
      </li>
      <li <%='class=selected' if current_page?(users_path)%>>
        <%= link_to 'Students', users_path %>
      </li>
      <li <%='class=selected' if current_page?(professors_path)%>>
        <%= link_to 'Professors', professors_path %>
      </li>
    </ul>
  </div>

app/views/users/_prof_nav.html.erb
  <div class='side-nav hidden-xs'>
    <a href='/'><%= image_tag('dashboard_logo.png') %></a>
    <ul>
      <li <%='class=selected' if current_page?(rosters_path)%>>
        <%= link_to 'My Classes', rosters_path %>
      </li>
      <li <%='class=selected' if current_page?(class_requests_path)%>>
        <%= link_to 'New Student Requests - ' + current_user.class_requests.select{ |cr| !cr.accepted}.size.to_s, class_requests_path %>
      </li>
    </ul>
  </div>

app/views/users/_user_nav.html.erb
  <div class='side-nav hidden-xs'>
    <a href='/'><%= image_tag('dashboard_logo.png') %></a>
    <ul>
      <li <%='class=selected' if current_page?(user_dashboard_path)%>>
        <%= link_to 'Belt Dashboard', user_dashboard_path %>
      </li>
      <li <%='class=selected' if current_page?(user_summary_path)%>>
        <%= link_to 'Videos', user_summary_path %>
      </li>
      <li <%='class=selected' if current_page?(rosters_path)%>>
        <%= link_to 'My Classes', rosters_path %>
      </li>
      <li <%='class=selected' if current_page?(feedback_path)%>>
        <%= link_to 'My Feedback', feedback_path %>
      </li>
    </ul>
  </div>
  
<nav class="navbar navbar-default visible-xs" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag('dashboard_logo.png', class: 'img-responsive') %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%='class=active' if current_page?(user_dashboard_path)%>>
          <%= link_to 'Belt Dashboard', user_dashboard_path %>
        </li>
        <li <%='class=active' if current_page?(user_summary_path)%>>
          <%= link_to 'Videos', user_summary_path %>
        </li>
        <li <%='class=active' if current_page?(rosters_path)%>>
          <%= link_to 'My Classes', rosters_path %>
        </li>
        <li <%='class=active' if current_page?(feedback_path)%>>
          <%= link_to 'My Feedback', feedback_path %>
        </li>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
      </ul>
    </div>
</nav>

app/views/users/admin_dashboard.html.erb
<div class='row'>
 <%= render 'admin_nav' %>


  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> Dashboard </h2>            
    </div>
  </div>
  
</div>

app/views/users/dashboard.html.erb
<%=@user.first_name%><br>
<%=@user.last_name%><br>
<%=@user.email%>

app/views/users/feedback.html.erb
<div class='row'>
  <%= render 'users/user_nav' %>
  <div class='col-sm-9'>
    <div class='roster lessons dashboard'>
      <h2>View Feedback</h2>        
      <table id='lessons' class='table table-striped'>
        <thead>
          <tr>
            <th width='70%' class ='left'>LESSON</th>
            <th>VIDEO VIEWS</th>
            <th>QUIZ ATTEMPTS</th>
            <th>AVG SCORE</th>
            <th>LATEST FEEDBACK</th>
          </tr>
        </thead>
        <tbody id='accordion' data-update-url="<%= sort_lessons_path %>">
          <% @lessons.each do |lesson| %>
          <tr id="lesson_<%= lesson.id %>">
            <td><%= lesson.title %></td>
            <td><%= @user.view_count(lesson.id) %></td>
            <td><%= @user.quiz_attempts(lesson.id).size %></td>
            <td><%= percent(@user.avg_score(lesson.id))%></td>
            <% quiz = @user.last_completed_quiz(lesson.id) %>
            <td><%= link_to 'LATEST FEEDBACK', quiz_feedback_path(quiz), class: 'btn btn-primary' unless quiz.nil? %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>


  <div class='lessons col-sm-9'>
    <div class='dashboard'>
      <h2> Members </h2>
      <input class='form-control' placeholder='Search Members...' id='member-search'>
  
  <table class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>Name</th>
          <th>Email</th>
          <th>Type</th>
          <th>School</th>
          <th>Last Quiz Score</th>
          <th>Last Belt</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.list_name, user_path(user) %></td>
            <td><a href='mailto:<%= user.email %>'><%= user.email %></a></td>
            <td><%= user.member_type %></td>
            <td><%= user.school.school if user.school.present? %></td>
            <td><%= percent(user.completed_quizzes.last.score) unless user.completed_quizzes.empty? %></td>
            <td><%= user.belts.last.belt unless user.belts.empty? %></td>
            <td><%= link_to "<i class='fa fa-trash-o'></i>".html_safe, user_path(user), method: :delete, data: { confirm: 'You are about to delete this member. This is irreversible. Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/professors_index.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>
 
 
  <div class='lessons col-sm-9'>
    <div class='dashboard'>
      <h2> Professors </h2>
  
  <table class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>Name</th>
          <th>Email</th>
          <th>University</th>
          <th>Number of Students</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @professors.each do |professor| %>
          <tr>
            <td><%= professor.list_name %></td>
            <td><%= professor.email %></td>
            <td><%= professor.school.school unless professor.school.nil?%></td>
            <td><%= link_to 'View Classes', user_path(professor) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>


  <div class='lessons col-sm-9'>
    <div class='summary dashboard'>
      <h2> Student Detail </h2>
      <div class='student-details'>
        <ul>
        <li> NAME: <%= @user.name %> </li>
        <% if @user.school.present? %>
        <li> SCHOOL: <%=@user.school.school%> </li>
        <% end %>
        </ul>
      </div>
  
  <table class='table table-striped'>
      <thead>
        <tr>
          <th>TOPIC</th>
          <th>VIEWS</th>
          <th>AVG SCORE</th>
          <th>ATTEMPTS</th>
        </tr>
      </thead>
      <tbody>
        <% @user.attempted_lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.title %></td>
            <td class='stat'><%= @user.view_count(lesson.id) %></td>
            <td class='stat'><%= percent(@user.avg_score(lesson.id)) %></td>
            <td class='stat'><%= @user.quiz_attempts(lesson.id).size %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show_professor.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>
 
 
  <div class='lessons col-sm-9'>
    <div class='dashboard'>
      <h2><%= @user.list_name %> - Classes </h2>
  
  <table class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>Class</th>
          <th>Professor</th>
          <th>Number of Students</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @rosters.each do |roster| %>
          <tr>
            <td><%= roster.title %></td>
            <td><%= roster.professor.list_name %></td>
            <td><%= roster.users.size %></td>
            <td><%= link_to 'More Details', roster_path(roster) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/summary.html.erb
<div class='row'>
  <%= render 'user_nav' %>
  
  <div class='col-sm-9'>
    <div class='summary dashboard'>
      <h2> Student Detail </h2>
      <div class='student-details'>
        <ul>
        <li> NAME: <%= @user.name %> </li>
        <li> SCHOOL: <%=@user.school.school unless @user.school.nil? %> </li>
        </ul>
      </div>
      
      <div class='student-stats'>
        <table>
          <thead>
            <tr>
              <th class ='left'>TOPIC</th>
              <th>VIEWS</th>
              <th>AVG SCORE</th>
              <th>ATTEMPTS</th>
              <th class='hidden-xs'>STATUS</th>
            </tr>
          </thead>
          <tbody>
            <% @lessons.each do |lesson| %>
              <tr>
                <td>
                  <%= lesson.title %>
                  <%= form_for @quiz, url: quizzes_path, html:{class: 'nifty_form'} do %>
                  <p class='lesson-links'>
                    <%= link_to 'View Video', lesson_path(lesson) %>
                    <span class='mdot'> &#183; </span>
                    <%= hidden_field_tag :lesson_id, lesson.id %>
                    <%= submit_tag 'Take Quiz', class: 'linkify' %>
                  </p>
                  <%end%>
                </td>
                <td class='stat'><%= @user.view_count(lesson.id) %></td>
                <td class='stat'><%= percent(@user.avg_score(lesson.id)) %></td>
                <td class='stat'><%= @user.quiz_attempts(lesson.id).size %></td>
                <td class='hidden-xs stat'>
                  <%= @user.completed_lessons.include?(lesson) ? 'Pass' : 'Fail' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      
    </div>
  </div>
</div>



<script>
  $(function() {
    videoView();
  })
</script>

app/views/users/user_dashboard.html.erb
<div class='row'>
 <%= render 'user_nav' %>


  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> Belt Dashboard </h2>
      
      <div class='stats-overview'>
        <h4> YOUR PROGRESS OVERVIEW </h4>
        <div class='header-break'></div>
        <div><strong>Progress toward a Ninja Status</strong></div>
        <div class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= percent(@user.ninja_status) %>">
            <%= percent(@user.ninja_status) %>
          </div>
        </div>
        <div class='current-belt'>
          <p class='header'>Current Belt</p>
          <%= image_tag('belt.png',class: "img-responsive #{@user.belts.last.present? ? @user.belts.last.belt : 'white' }" ) %>
        </div>
      </div>

      <div class='current-lesson'>
        <div class='header'>
          <h4> CURRENT ASSIGNMENT <a data-toggle='modal' class='view-all-belts' data-target='#myModal' href=''>View All Videos for This Belt</a> </h4> 
          <div class='header-break'></div>
          Topic: <strong><%= @lesson.title %></strong>
        </div>
        
        
        <div class='video-preview'>
          <% @lesson.videos.each do |video| %>
            <video controls="controls" data-user-id=<%=@user.id%> data-video-id=<%=video.id%>>
              <source src=<%=video.video%> type=<%=video.video_content_type%>>
              <source src=<%=video.ogv_video%> type=<%=video.ogv_video_content_type%>>
            </video>
          <% end %>
        </div>
        <div class='take-assessment'>
          <%= form_for @quiz, url: quizzes_path, html:{class: 'nifty_form'} do %>
            <%= hidden_field_tag :lesson_id, @lesson.id %>
          <%= submit_tag 'TAKE THE QUIZ', class: 'btn btn-primary btn-lg' %>
          <%end%>
        </div>
      </div>
            
      <div class='lesson-stats'>
        <ul>
          <li>
            <div class='header'>Views</div>
            <div class='stat'><%= @user.view_count(@lesson.id) %></div>
          </li>
          <li>
            <div class='header'>Quiz Attempts</div>
            <div class='stat'><%= @user.quiz_attempts(@lesson.id).size %></div>
          </li>
          <li>
            <div class='header'>Average Score</div>
            <div class='stat'><%= percent(@user.avg_score(@lesson.id)) %></div>
          </li>
          <li>
            <div class='challenged-belts'>
              <div class='header'>Challenged Belt</div>
              <div><%= image_tag('belt.png', class: @lesson.belt.belt) %></div>
            </div>
          </li>
        </ul>
      </div>
      
      <div class='belts-earned'>
        <h4> EARNED BELTS </h4>
        <div class='header-break'></div>
        <div class='earned-belts'>
          <ul>
            <li>
              <%= image_tag('belt.png',class: "img-responsive white" ) %>
            </li>
            <% Belt.all.each do |belt| %>
            <li>
              <%= image_tag('belt.png',class: "img-responsive #{@user.belts.include?(belt) ? belt.belt : 'gray' }" ) %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Lessons Remaining to Earn Belt</h4>
      </div>
      <div class="challenged-lessons-modal-body modal-body">
        <table id='lessons-challenged-belt' class='table table-striped'>
          <tbody>
            <% @lesson.belt.lessons.each do |lesson| %>
            <tr>
              <td class='left'>
                <% if @user.completed_lessons.include?(lesson) %>
                  <i class="fa fa-check"></i>
                <% end %>
              </td>
              <td>
                <%= lesson.title %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class='challenged-belt-modal'>
          <div class='header'>Challenged Belt</div>
          <div><%= image_tag('belt.png', class: @lesson.belt.belt) %></div>
        </div>
      </div>
      <div class="challenged-belts-close modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    videoView();
  })
</script>