config/routes.rb
ThatStatBook::Application.routes.draw do
  devise_for :users, :controllers => { :passwords => 'passwords', :registrations => 'registrations' }

  root 'pages#welcome'

  get '/home' => 'users#dashboard', as: :user_dashboard
  get '/summary' => 'users#summary', as: :user_summary
  get '/feedback' => 'users#feedback', as: :feedback
  
  resources :users, only: [:show,:index,:destroy]
  resources :lessons, only: [:show,:index,:update,:destroy,:new,:create] do
    collection { post :sort }
    resources :questions, only: [:new,:create]
    resources :videos, only: [:new,:create]
    resources :learning_modules, only: [:index,:create,:new,:destroy]
  end
  
  resources :learning_modules, only: [:update]
  resources :quizzes, only: [:create,:show]
  resources :questions, only: [:show,:destroy,:update]
  resources :choices, only: [:show,:update]
  resources :answer_submissions, only: [:create]
  resources :video_views, only: [:create]
  
  resources :rosters, only: [:index,:show,:new,:update,:create]
  
  resources :class_requests, only: [:create, :index]
  
  resources :suggestions do
    get :autocomplete_school_school, :on => :collection
  end

  get '/questions/:id/update_learning_module/:learning_module_id' => 'questions#update_learning_module'

  get '/quizzes/:quiz_id/new-question' => 'questions#show_random_question', as: :random_question
  get '/quizzes/:quiz_id/incomplete' => 'quizzes#incomplete'
  get '/quizzes/:quiz_id/certificate' => 'quizzes#certificate', as: :certificate
  get '/quizzes/:id/feedback' => 'quizzes#feedback', as: :quiz_feedback
  
  get 'rearrange' => 'lessons#rearrange'
  
  get 'password-reset' =>'pages#password_reset', as: :password_reset
  
  post '/countdown' => 'quizzes#countdown'
  
  get '/questions/:id/delete_image' => 'questions#delete_image', as: :delete_question_image
  
  patch '/rosters/:id/add_students' => 'rosters#add_students', as: :add_students
  post '/rosters/:id/remove_student/:user_id' => 'rosters#remove_student', as: :remove_student  
  get '/rosters-prof/:prof_id' => 'rosters#get_rosters_by_prof' 
  
  get '/rosters/:roster_id/students/:student_id' => 'rosters#show_roster_student', as: :student_roster

  get '/class_requests/:id/accept' => 'class_requests#accept', as: :accept_class_request
  get '/class_requests/:id/reject' => 'class_requests#reject', as: :reject_class_request
  
  get '/professors' => 'users#professors_index', as: :professors

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :questions
  has_many :quizzes, :dependent => :destroy
  has_many :videos, :dependent => :destroy
  has_many :learning_modules
  has_and_belongs_to_many :rosters
  belongs_to :belt
  validates_presence_of :title
  validates_uniqueness_of :level
  validates_presence_of :level
  
  def self.levels
    Lesson.pluck(:level).sort!
  end
  
  def active_questions
    self.questions.where(active: true)
  end
  
  def self.create_empty(level)
    max_level = levels.max
    max_level.downto(level) do |x|
      lesson = Lesson.find_by(level: x)
      lesson.level += 1
      lesson.save
    end
  end
  
  def self.fill_empty(level)
    max_level = levels.max
    level += 1
    level.upto(max_level) do |x|
      lesson = Lesson.find_by(level: x)
      lesson.level -= 1
      lesson.save
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @user = current_user
    @lesson = Lesson.find(params[:id])
    unless current_user.student?
      @learning_module = @lesson.learning_modules.new
      @learning_modules = @lesson.learning_modules
      @questions = @lesson.questions.select { |q| q.active == true }
      respond_to do |format|
        format.html {render :show}
        format.json {render :json => @lesson}
      end
    else
      @quiz = Quiz.new
      render :show_student
    end
  end
  
  def index
    if current_user.admin?
      @lessons = Lesson.all.sort_by { |lesson| lesson.level }
      render :index
    else
      render text: 'Restricted'
    end
  end
  
  def update
    if current_user.admin?
      @lesson = Lesson.find(params[:id])
      if @lesson.update_attributes!(update_lesson_params)
        respond_to do |format|
          format.json { render :json => @lesson }
        end
      else
        respond_to do |format|
          format.html { render :action  => :edit } # edit.html.erb
          format.json { render :nothing =>  true }
        end
      end
    end
  end
  
  def destroy
    if current_user.admin?
      @lesson = Lesson.find(params[:id])
      destroyed_level = @lesson.level
      @lesson.destroy
      Lesson.fill_empty(destroyed_level)
      redirect_to lessons_path
    end
  end
  
  def new
    if current_user.admin?
     @lesson = Lesson.new 
    end
  end
  
  def create
    if current_user.admin?
      @lesson = Lesson.new(lesson_params)
      belt_max_level = @lesson.belt.max_level
      Lesson.create_empty(belt_max_level)
      @lesson.level = belt_max_level
      if @lesson.save
        redirect_to lesson_path(@lesson)
      else
        render text: 'ERROR'
      end
    end
  end
  
  def rearrange
    @belt_lessons = Belt.sorted_lessons
  end
  
  def sort
    new_levels = params[:lesson].keys
    new_levels.each_with_index do |id, index|
      new_level = index + 1
      Lesson.update_all({level: new_level, belt_id: Belt.find_by(belt: params[:lesson][id.to_s]).id},{id: id})
    end
    render nothing: true
  end
  
  private

  def lesson_params
    params.require(:lesson).permit(:title,:belt_id)
  end
  def update_lesson_params
    params.require(:lesson).permit(:title)
  end
end

app/views/lessons/index.html.erb
<div class='row'>
 <%= render 'users/admin_nav' %>


 <div class='col-sm-9'>
  <div class='lessons dashboard'>
    <h2> Lessons </h2>        
    <%= link_to 'New Lesson', new_lesson_path, class: 'btn btn-primary' %> 
    <%= link_to 'Rearrange', rearrange_path, class: 'btn btn-primary' %> 
    <table id='lessons' class='table table-striped'>
      <thead>
        <tr>
          <th class ='left'>TOPIC</th>
          <th>LEVEL</th>
          <th>BELT</th>
          <th>QUESTIONS</th>
          <th></th>
        </tr>
      </thead>
      <tbody data-update-url="<%= sort_lessons_path %>">
        <% @lessons.each do |lesson| %>
        <tr id="lesson_<%= lesson.id %>">
          <td><%= link_to lesson.title, lesson_path(lesson) %></td>
          <td class='level'><%= lesson.level %></td>
          <td><%= lesson.belt.belt %></td>
          <td><%= lesson.active_questions.size %></td>
          <td>
            <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, lesson_path(lesson), method: :delete, data: { confirm: 'You are about to delete a lesson. This is irreversible. Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/lessons/new.html.erb
<div class='row'>
  <%= render 'users/admin_nav' %>
  
  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> New Lesson </h2>
      <%= bootstrap_form_for @lesson, url: lessons_path do |f| %>
      <%= f.text_field :title, required: true %>
      <%= f.select(:belt_id, options_for_select(Belt.pluck(:belt,:id)) ) %>
      <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
      
  

app/views/lessons/rearrange.html.erb
<div class='row'>
  <%= render 'users/admin_nav' %>
  
  <div class='col-sm-9'>
    <div class='dashboard'>
      <h2> Rearrange Lessons </h2>
      <div class='rearrange'>
      <ol class="sortable">
      <% @belt_lessons.each do |belt,lessons| %>
        <li id='belt_<%= belt.belt %>' class='belt'>
            <div><%= belt.belt.capitalize %></div>
            
            <ol>
            <% lessons.each do |lesson| %>
              <li id='lesson_<%= lesson.id %>' class='lesson'>
                <div><%= lesson.title %></div>
              </li>
            <% end %>
              <li class='lesson'><div>&nbsp;</div></li>
            </ol>
            
        </li>
      <% end %>
      </ol>
      </div>
    </div>
  </div>
</div>
      
      

  

app/views/lessons/restricted.html.erb
<h2>Sorry You Do Not Have Access To This Lesson!</h2>

app/views/lessons/show.html.erb
<div class='row'>
  <% if @user.admin? %>
    <%= render 'users/admin_nav' %>
  <% else %>
    <%= render 'users/prof_nav' %>
  <% end %>
 


  <div class='lessons col-sm-10'>
    <div class='dashboard'>
      <h2> Lesson: 
        <span class="rest-in-place" data-url="/lessons/<%=@lesson.id%>" data-object="lesson" data-attribute="title" data-placeholder="lesson">
          <%=@lesson.title%>
        </span>
      </h2>
      <div class='video-preview'>
        <% @lesson.videos.each do |video| %>
          <video controls="controls">
            <source src=<%=video.video%> type=<%=video.video_content_type%>>
            <source src=<%=video.ogv_video%> type=<%=video.ogv_video_content_type%>>
          </video>
        <% end %>
      </div>
      <div>
        <% if @user.admin? %>
        <%= link_to 'New Question', new_lesson_question_path(@lesson), class: 'btn btn-primary' %>
        <%= link_to 'Add/Change Video', new_lesson_video_path(@lesson), class: 'new-video-load btn btn-primary' %>
        
        <%= link_to 'Add/Change Dev Topic Areas', lesson_learning_modules_path(@lesson), class: 'btn btn-primary' %>

        <% end %>
      </div>
      
      <% if @user.admin? %>
      <table class='table table-striped'>
          <thead>
            <tr>
              <th width='25%' class ='left'>QUESTION</th>
              <th width='25%'>ANSWER</th>
              <th width='25%'>DEV TOPIC AREA</th>
              <th>PERCENT CORRECT</th>
              <th>CORRECT ATTEMPTS</th>
              <th>TOTAL ATTEMPTS</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @questions.each do |question| %>
              <tr>
                <td><%= link_to question.question, question_path(question) %></td>
                <td class='stat'><%= question.answer.choice %></td>
                <td>
                  <div class="dropdown">
                    <div class='dropdown-title'>
                      <button class="btn dropdown-toggle" type="button" id="qlm<%=question.id%>" data-toggle="dropdown">
                        <%= question.learning_module.nil? ? '(None Selected)' : question.learning_module.title %> </a>
                      </button>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="qlm<%=question.id%>">
                        <% @learning_modules.each do |learning_module| %>
                          <li role="presentation">
                            <a role="menuitem" tabindex="-1" href="/questions/<%= question.id %>/update_learning_module/<%= learning_module.id %>">
                              <%= learning_module.title %>
                            </a>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                  
                </td>
                <td><%= percent(question.percent_correct) %></td>
                <td><%= question.correct_attempts %></td>
                <td><%= question.total_attempts %></td>
                <td>
                  <% if @user.admin? %>
                  <%= link_to "<i class='fa fa-trash-o'></i>".html_safe, question_path(question), method: :delete, data: { confirm: 'You are about to delete a question. This is irreversible. Are you sure?' } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
      
      </div>
    </div>
  </div>


<script>
$(document).ready(function() {
  videoLoad();
  });
</script>

app/views/lessons/show_student.html.erb
<div class='row'>
  <%= render 'users/user_nav' %>
 


  <div class='lessons col-sm-10'>
    <div class='dashboard'>
      <%= link_to "< All Videos", user_summary_path %>
      <h2> Lesson: <%=@lesson.title%></h2>
      <div class='video-preview'>
        <% @lesson.videos.each do |video| %>
          <video controls="controls" data-user-id=<%=@user.id%> data-video-id=<%=video.id%>>
            <source src=<%=video.video%> type=<%=video.video_content_type%>>
            <source src=<%=video.ogv_video%> type=<%=video.ogv_video_content_type%>>
          </video>
        <% end %>
      </div>
      <%= form_for @quiz, url: quizzes_path, html:{class: 'nifty_form'} do |f| %>
        <%= hidden_field_tag :lesson_id, @lesson.id %>
        <%= submit_tag 'Take Quiz', class: 'btn btn-lg btn-primary linkify' %>
      <%end%>
    </div>
  </div>


<script>
$(document).ready(function() {
  videoLoad();
  videoView();
  });
</script>